function eqn2 = compute_ddtheta2(I1,I2,d1,d2,dtheta1,dtheta2,g,l1,m1,m2,tau1,tau2,theta1,theta2)
%COMPUTE_DDTHETA2
%    EQN2 = COMPUTE_DDTHETA2(I1,I2,D1,D2,DTHETA1,DTHETA2,G,L1,M1,M2,TAU1,TAU2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Nov-2016 15:52:27

t2 = d2.^2;
t3 = l1.^2;
t4 = d1.^2;
t5 = m2.^2;
t6 = cos(theta2);
t7 = cos(theta1);
t8 = dtheta1.^2;
t9 = sin(theta2);
t10 = theta1+theta2;
t11 = cos(t10);
t12 = dtheta2.^2;
eqn2 = -(-I1.*tau2+I2.*tau1-I2.*tau2+m2.*t2.*tau1-m2.*t2.*tau2-m1.*t4.*tau2-m2.*t3.*tau2+I1.*d1.*g.*m1.*t7+I1.*d2.*g.*m2.*t11+I1.*g.*l1.*m2.*t7+d2.*l1.*m2.*t6.*tau1-d2.*l1.*m2.*t6.*tau2.*2.0+d2.*g.*t3.*t5.*t11+g.*l1.*t3.*t5.*t7+d1.*g.*m1.^2.*t4.*t7+g.*l1.*t2.*t5.*t6.*t11+t2.*t3.*t5.*t6.*t8.*t9.*2.0+t2.*t3.*t5.*t6.*t9.*t12+I1.*d2.*l1.*m2.*t8.*t9+I2.*d2.*l1.*m2.*t8.*t9+I2.*d2.*l1.*m2.*t9.*t12+d1.*g.*m1.*m2.*t3.*t7+d2.*g.*m1.*m2.*t4.*t11+g.*l1.*m1.*m2.*t4.*t7+d2.*g.*t3.*t5.*t6.*t7+d2.*l1.*t2.*t5.*t8.*t9+d2.*l1.*t3.*t5.*t8.*t9+d2.*l1.*t2.*t5.*t9.*t12+I2.*d2.*dtheta1.*dtheta2.*l1.*m2.*t9.*2.0+d2.*dtheta1.*dtheta2.*l1.*t2.*t5.*t9.*2.0+d2.*l1.*m1.*m2.*t4.*t8.*t9+dtheta1.*dtheta2.*t2.*t3.*t5.*t6.*t9.*2.0+d1.*d2.*g.*l1.*m1.*m2.*t6.*t7)./(I1.*I2+I1.*m2.*t2+I2.*m1.*t4+I2.*m2.*t3+t2.*t3.*t5+m1.*m2.*t2.*t4-t2.*t3.*t5.*t6.^2);
