function eqn1 = compute_ddtheta1(I1,I2,d1,d2,dtheta1,dtheta2,g,l1,m1,m2,tau1,tau2,theta1,theta2)
%COMPUTE_DDTHETA1
%    EQN1 = COMPUTE_DDTHETA1(I1,I2,D1,D2,DTHETA1,DTHETA2,G,L1,M1,M2,TAU1,TAU2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Nov-2016 15:52:27

t2 = d2.^2;
t3 = l1.^2;
t4 = d1.^2;
t5 = m2.^2;
t6 = cos(theta2);
t7 = sin(theta2);
t8 = dtheta1.^2;
t9 = dtheta2.^2;
t10 = cos(theta1);
eqn1 = (I2.*tau1-I2.*tau2+m2.*t2.*tau1-m2.*t2.*tau2-d2.*l1.*m2.*t6.*tau2+t2.*t3.*t5.*t6.*t7.*t8+g.*l1.*t2.*t5.*t6.*cos(theta1+theta2)+I2.*d2.*l1.*m2.*t7.*t8+I2.*d2.*l1.*m2.*t7.*t9+d2.*g.*t3.*t5.*t6.*t10+d2.*l1.*t2.*t5.*t7.*t8+d2.*l1.*t2.*t5.*t7.*t9+I2.*d2.*dtheta1.*dtheta2.*l1.*m2.*t7.*2.0+d2.*dtheta1.*dtheta2.*l1.*t2.*t5.*t7.*2.0+d1.*d2.*g.*l1.*m1.*m2.*t6.*t10)./(I1.*I2+I1.*m2.*t2+I2.*m1.*t4+I2.*m2.*t3+t2.*t3.*t5+m1.*m2.*t2.*t4-t2.*t3.*t5.*t6.^2);
