function tau2Eq = grav_comp_tau2(d1,d2,dtheta1,g,l1,m1,m2,theta1,theta2)
%GRAV_COMP_TAU2
%    TAU2EQ = GRAV_COMP_TAU2(D1,D2,DTHETA1,G,L1,M1,M2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Nov-2016 15:52:29

t2 = cos(theta1);
tau2Eq = d1.*g.*m1.*t2+g.*l1.*m2.*t2+d2.*g.*m2.*cos(theta1+theta2)+d2.*dtheta1.^2.*l1.*m2.*sin(theta2);
