function tau1Eq = grav_comp_tau1(d1,d2,dtheta1,dtheta2,g,l1,m1,m2,theta1,theta2)
%GRAV_COMP_TAU1
%    TAU1EQ = GRAV_COMP_TAU1(D1,D2,DTHETA1,DTHETA2,G,L1,M1,M2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Nov-2016 15:52:29

t2 = cos(theta1);
t3 = sin(theta2);
tau1Eq = d1.*g.*m1.*t2+g.*l1.*m2.*t2+d2.*g.*m2.*cos(theta1+theta2)-d2.*dtheta2.^2.*l1.*m2.*t3-d2.*dtheta1.*dtheta2.*l1.*m2.*t3.*2.0;
